// Image map для всех блюд меню
// Локальные изображения из docx файла

const imageMapData: Record<string, string> = {
  'Хинкали с говядиной и свининой': '/menu/image7.jpeg',
  'Хинкали с телятиной': '/menu/image8.png',
  'Хинкали с бараниной': '/menu/image9.png',
  'Хинкали с бараниной и брынзой': '/menu/image10.png',
  'Хинкали с грибами': '/menu/image24.png',
  'Хинкали с сыром': '/menu/image25.png',
  'Бакинские томаты с имеретинским сыром и соусом песто': '/menu/image26.png',
  'Сельдь с теплым картофелем и луком': '/menu/image27.png',
  'Ассорти из грузинского домашнего сыра': '/menu/image28.png',
  'Грузинские соленья': '/menu/image29.png',
  'Ассорти из свежих овощей': '/menu/image30.png',
  'Тарелка к пиву': '/menu/image31.png',
  'Мясное плато': '/menu/image32.png',
  'Ростбиф': '/menu/image33.png',
  'Хрустящие баклажаны с соусом Тай Чили': '/menu/image34.png',
  'Ассорти пхали': '/menu/image35.jpeg',
  'Рулетики из баклажанов': '/menu/image36.png',
  'Шампиньоны запечённые с сыром': '/menu/image37.png',
  'Сырные палочки в хрустящей панировке': '/menu/image38.jpeg',
  'Салат из бакинских томатов и огурцов': '/menu/image39.png',
  'Цезарь с курицей': '/menu/image40.png',
  'Цезарь с креветками': '/menu/image41.png',
  'Фирменный Салат Ван Гоги': '/menu/image42.png',
  'Теплый салат с языком': '/menu/image43.png',
  'Салат Тбилиси от Шеф-повара': '/menu/image44.png',
  'Салат из хрустящих баклажанов с сыром Страчателла': '/menu/image45.png',
  'Салат из булгура со свежими овощами': '/menu/image46.png',
  'Салат Тевзи': '/menu/image47.jpeg',
  'Салат Мамали': '/menu/image48.jpeg',
  'Салат из ростбифа': '/menu/image49.jpeg',
  'Харчо': '/menu/image7.jpeg',
  'Кюфта по-Турецки с нутом': '/menu/image7.jpeg',
  'Борщ с салом и чесночком': '/menu/image7.jpeg',
  'Суп Дюшбара - Говырма': '/menu/image7.jpeg',
  'Суп тыквенный': '/menu/image7.jpeg',
  'Куриный суп с домашней лапшой': '/menu/image7.jpeg',
  'Буглама из ягненка': '/menu/image7.jpeg',
  'Говурма из ягнёнка': '/menu/image7.jpeg',
  'Долма': '/menu/image7.jpeg',
  'Оджахури из свинины': '/menu/image7.jpeg',
  'Оджахури из телятины': '/menu/image7.jpeg',
  'Цыпленок тапака с мятым картофелем': '/menu/image7.jpeg',
  'Чкмерули': '/menu/image7.jpeg',
  'Стейк из мраморной говядины с картофелем по-деревенски': '/menu/image7.jpeg',
  'Стейк из свиной шеи с капустой по-гурийски': '/menu/image7.jpeg',
  'Филе судака на овощной подушке': '/menu/image7.jpeg',
  'Терпуг Камчатский запечённый': '/menu/image7.jpeg',
  'Треска во фритюре с кисло-сладким соусом и картошкой фри': '/menu/image7.jpeg',
  'Киресуз из телятины': '/menu/image7.jpeg',
  'Овощи на пару': '/menu/image7.jpeg',
  'Мятый картофель с чесноком': '/menu/image7.jpeg',
  'Грузинский Шоти': '/menu/image7.jpeg',
  'Хачапури по - Аджарски': '/menu/image7.jpeg',
  'Хачапури по - Мегрельски': '/menu/image7.jpeg',
  'Хачапури по - Мегрельски на компанию': '/menu/image7.jpeg',
  'Кубдари': '/menu/image7.jpeg',
  'Кубдари на компанию': '/menu/image7.jpeg',
  'Хачапури по-Турецки': '/menu/image7.jpeg',
  'Гюзлама с курицей и сыром': '/menu/image7.jpeg',
  'Гюзлама с курицей и сыром на компанию': '/menu/image7.jpeg',
  'Чебурек': '/menu/image7.jpeg',
  'Кутабы': '/menu/image7.jpeg',
};

export const imageMap: Record<string, string> = imageMapData;

// Функция для получения URL изображения по названию блюда
export function getImageUrl(itemName: string): string {
  return imageMap[itemName] || '';
}
