// Image map для всех блюд меню
// Локальные изображения из menu.json

const baseUrl = import.meta.env.BASE_URL || '/vangogi/';

const imageMapData: Record<string, string> = {
  'Аджика': `${baseUrl}menu/image48.jpg`,
  'Ассорти из грузинского домашнего сыра': `${baseUrl}menu/image3.png`,
  'Ассорти из свежих овощей': `${baseUrl}menu/image5.png`,
  'Ассорти пхали': `${baseUrl}menu/image9.png`,
  'Бакинские томаты с имеретинским сыром и соусом песто': `${baseUrl}menu/image1.png`,
  'Борщ с салом и чесночком': `${baseUrl}menu/image23.png`,
  'Буглама из ягненка': `${baseUrl}menu/image27.png`,
  'Говурма из ягнёнка': `${baseUrl}menu/image28.png`,
  'Грузинские соленья': `${baseUrl}menu/image4.png`,
  'Грузинский Шоти': `${baseUrl}menu/image39.png`,
  'Гюзлама с курицей и сыром': `${baseUrl}menu/image44.png`,
  'Гюзлама с курицей и сыром на компанию': `${baseUrl}menu/image44.png`,
  'Гюзлама с курицей и сыром на одного': `${baseUrl}menu/image44.png`,
  'Долма': `${baseUrl}menu/image38.jpg`,
  'Киресуз из телятины': `${baseUrl}menu/image31.png`,
  'Кубдари': `${baseUrl}menu/image42.png`,
  'Кубдари на компанию': `${baseUrl}menu/image42.png`,
  'Куриный суп с домашней лапшой': `${baseUrl}menu/image25.png`,
  'Кутабы': `${baseUrl}menu/image46.png`,
  'Кюфта по-Турецки с нутом': `${baseUrl}menu/image22.png`,
  'Мясное плато': `${baseUrl}menu/image7.jpg`,
  'Мятый картофель с чесноком': `${baseUrl}menu/image32.png`,
  'Овощи на пару': `${baseUrl}menu/image5.png`,
  'Оджахури из свинины': `${baseUrl}menu/image30.png`,
  'Оджахури из телятины': `${baseUrl}menu/image31.png`,
  'Ростбиф': `${baseUrl}menu/image34.png`,
  'Рулетики из баклажанов с начинкой из грецких орехов': `${baseUrl}menu/image11.jpg`,
  'Салат Мамали': `${baseUrl}menu/image19.png`,
  'Салат Тбилиси от Шеф-повара': `${baseUrl}menu/image19.png`,
  'Салат Тевзи': `${baseUrl}menu/image19.png`,
  'Салат из бакинских томатов и огурцов': `${baseUrl}menu/image14.png`,
  'Салат из булгура со свежими овощами': `${baseUrl}menu/image5.png`,
  'Салат из ростбифа': `${baseUrl}menu/image34.png`,
  'Салат из хрустящих баклажанов с сыром Страчателла': `${baseUrl}menu/image20.png`,
  'Сельдь с теплым картофелем и луком': `${baseUrl}menu/image2.png`,
  'Сметана': `${baseUrl}menu/image50.png`,
  'Стейк из мраморной говядины с картофелем по-деревенски': `${baseUrl}menu/image34.png`,
  'Стейк из свиной шеи с капустой по-гурийски': `${baseUrl}menu/image30.png`,
  'Суп Дюшбара - Говырма': `${baseUrl}menu/image28.png`,
  'Суп тыквенный': `${baseUrl}menu/image24.png`,
  'Сырные палочки в хрустящей панировке': `${baseUrl}menu/image13.png`,
  'Тарелка к пиву': `${baseUrl}menu/image6.png`,
  'Теплый салат с языком': `${baseUrl}menu/image18.png`,
  'Терпуг Камчатский запечённый': `${baseUrl}menu/image36.png`,
  'Ткемали': `${baseUrl}menu/image47.jpg`,
  'Томатный': `${baseUrl}menu/image49.jpg`,
  'Треска во фритюре с кисло-сладким соусом и картошкой фри': `${baseUrl}menu/image37.png`,
  'Филе судака на овощной подушке': `${baseUrl}menu/image35.jpg`,
  'Фирменный Салат Ван Гоги': `${baseUrl}menu/image17.png`,
  'Харчо': `${baseUrl}menu/image21.png`,
  'Хачапури по - Аджарски': `${baseUrl}menu/image40.png`,
  'Хачапури по - Мегрельски': `${baseUrl}menu/image41.png`,
  'Хачапури по - Мегрельски на компанию': `${baseUrl}menu/image41.png`,
  'Хачапури по-Турецки': `${baseUrl}menu/image43.png`,
  'Хинкали с бараниной': `${baseUrl}menu/image26.png`,
  'Хинкали с бараниной и брынзой': `${baseUrl}menu/image26.png`,
  'Хинкали с говядиной и свининой': `${baseUrl}menu/image26.png`,
  'Хинкали с грибами': `${baseUrl}menu/image26.png`,
  'Хинкали с сыром': `${baseUrl}menu/image26.png`,
  'Хинкали с телятиной': `${baseUrl}menu/image26.png`,
  'Хрустящие баклажаны с соусом Тай Чили': `${baseUrl}menu/image8.png`,
  'Цезарь с креветками': `${baseUrl}menu/image16.png`,
  'Цезарь с курицей': `${baseUrl}menu/image15.png`,
  'Цыпленок тапака с мятым картофелем': `${baseUrl}menu/image32.png`,
  'Цыпленок тапака с толченным картофелем': `${baseUrl}menu/image32.png`,
  'Чебурек': `${baseUrl}menu/image45.png`,
  'Чкмерули': `${baseUrl}menu/image33.png`,
  'Шампиньоны запечённые с сыром': `${baseUrl}menu/image12.png`,
};

export const imageMap: Record<string, string> = imageMapData;

// Функция для получения URL изображения по названию блюда
export function getImageUrl(itemName: string): string {
  return imageMap[itemName] || '';
}
